#:schema node_modules/wrangler/config-schema.json
name = "stello"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"
pages_build_output_dir = "./build/client"

[build]
command = "pnpm run build"

[miniflare]
kv_persist = false
cache_persist = false
durable_objects_persist = false
