#:schema node_modules/wrangler/config-schema.json
name = "stello"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-01-01"
pages_build_output_dir = "./build/client"
send_metrics = false

[build]
command = "pnpm run build"
watch_dir = "build/client"

[env.production]
workers_dev = true

[miniflare]
kv_persist = false
cache_persist = false
durable_objects_persist = false
watch = false
update_check = false
